# Generated by Django 5.2.6 on 2025-10-01 20:45

import django_fsm
import django_mongodb_backend.fields
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_add_configurable_workflow_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='پیوست', max_length=200),
        ),
        migrations.AddField(
            model_name='workflowstatestep',
            name='form_number',
            field=models.IntegerField(blank=True, help_text='Form number for this step (if step requires form submission)', null=True),
        ),
        migrations.AddField(
            model_name='workflowstatestep',
            name='form_schema',
            field=models.JSONField(blank=True, help_text='Custom form schema for this step (JSON Schema format)', null=True),
        ),
        migrations.AddField(
            model_name='workflowstatestep',
            name='required_role_code',
            field=models.CharField(blank=True, help_text='Role code required to approve this step', max_length=100),
        ),
        migrations.AlterField(
            model_name='action',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='state',
            field=django_fsm.FSMField(choices=[('ApplicantRequest', 'Applicantrequest'), ('CEOInstruction', 'Ceoinstruction'), ('Form1', 'Form1'), ('Form2', 'Form2'), ('DocsCollection', 'Docscollection'), ('Form3', 'Form3'), ('Form4', 'Form4'), ('AMLForm', 'Amlform'), ('EvaluationCommittee', 'Evaluationcommittee'), ('AppraisalFeeDeposit', 'Appraisalfeedeposit'), ('AppraisalNotice', 'Appraisalnotice'), ('AppraisalOpinion', 'Appraisalopinion'), ('AppraisalDecision', 'Appraisaldecision'), ('Settlment', 'Settlment')], default='ApplicantRequest', max_length=50, protected=True),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['workflow', 'state', 'step'], name='workflows_a_workflo_c31e07_idx'),
        ),
        migrations.AlterModelTable(
            name='workflow',
            table=None,
        ),
    ]
