# Generated by Django 5.2.6 on 2025-10-03 22:03

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_add_form_to_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('form_number', models.IntegerField(help_text='Unique form number', unique=True)),
                ('title_en', models.CharField(help_text='Form title in English', max_length=255)),
                ('title_fa', models.CharField(help_text='Form title in Persian', max_length=255)),
                ('state', models.CharField(blank=True, help_text='Workflow state this form belongs to (optional)', max_length=64, null=True)),
                ('has_multiple_steps', models.BooleanField(default=False, help_text='If true, this form has multiple approval/fill steps')),
                ('total_steps', models.IntegerField(default=1, help_text='Total number of steps if multi-step form')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in workflow sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Form',
                'verbose_name_plural': 'Dynamic Forms',
                'ordering': ['display_order', 'form_number'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Machine-readable field code (e.g., 'firstName')", max_length=128)),
                ('label_en', models.CharField(help_text='Field label in English', max_length=255)),
                ('label_fa', models.CharField(help_text='Field label in Persian', max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Text Area'), ('NUMBER', 'Number'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('DATE', 'Date'), ('DATETIME', 'Date & Time'), ('BOOLEAN', 'Checkbox'), ('SELECT', 'Dropdown'), ('RADIO', 'Radio Button'), ('FILE', 'File Upload'), ('SIGNATURE', 'Digital Signature'), ('SECTION_HEADER', 'Section Header')], default='TEXT', max_length=32)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('options_json', models.JSONField(blank=True, help_text='JSON configuration for field (e.g., dropdown options, validation rules)', null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('regex_pattern', models.CharField(blank=True, help_text='Regex validation pattern', max_length=500)),
                ('validation_message', models.CharField(blank=True, help_text='Custom validation error message', max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('css_class', models.CharField(blank=True, help_text='CSS classes for styling', max_length=255)),
                ('default_value', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ['form', 'section', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Machine-readable section code (e.g., 'legalDeputyReport')", max_length=128)),
                ('title_en', models.CharField(max_length=255)),
                ('title_fa', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('required_step', models.IntegerField(blank=True, help_text='Step number required to access this section (for multi-step forms)', null=True)),
                ('requires_signature', models.BooleanField(default=False, help_text='Does this section require a signature?')),
                ('signature_field_code', models.CharField(blank=True, help_text="Field code for signature (e.g., 'managerSignature')", max_length=128, null=True)),
                ('signature_step', models.IntegerField(blank=True, help_text='Step number for signature approval', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'ordering': ['form', 'display_order'],
            },
        ),
        migrations.RenameIndex(
            model_name='workflowstatestep',
            new_name='workflows_w_state_i_38c084_idx',
            old_name='workflows_w_state_i_d23456_idx',
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(help_text='Parent form (required if no section)', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflows.dynamicform'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='workflows.dynamicform'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section this field belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflows.formsection'),
        ),
        migrations.AlterUniqueTogether(
            name='formsection',
            unique_together={('form', 'code')},
        ),
    ]
