# Generated by Django 5.2.6 on 2025-10-03 22:33

from django.db import migrations, models
import django.db.models.deletion


def migrate_role_codes_to_fk(apps, schema_editor):
    """Migrate existing role codes to ForeignKey relationships"""
    WorkflowStateStep = apps.get_model('workflows', 'WorkflowStateStep')
    OrgRole = apps.get_model('accounts', 'OrgRole')

    for step in WorkflowStateStep.objects.all():
        if step.required_role_code:
            try:
                role = OrgRole.objects.get(code=step.required_role_code)
                step.required_role = role
                step.save(update_fields=['required_role'])
            except OrgRole.DoesNotExist:
                print(f"Warning: Role '{step.required_role_code}' not found for step {step.id}")


def reverse_migrate(apps, schema_editor):
    """Reverse migration - copy role code back from FK"""
    WorkflowStateStep = apps.get_model('workflows', 'WorkflowStateStep')

    for step in WorkflowStateStep.objects.all():
        if step.required_role:
            step.required_role_code = step.required_role.code
            step.save(update_fields=['required_role_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_dynamicform_formfield_formsection_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Add new ForeignKey field (nullable initially)
        migrations.AddField(
            model_name='workflowstatestep',
            name='required_role',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='workflow_steps',
                to='accounts.orgrole',
                help_text='Role required to approve this step'
            ),
        ),
        # Migrate data from required_role_code to required_role FK
        migrations.RunPython(migrate_role_codes_to_fk, reverse_migrate),
        # Remove old CharField
        migrations.RemoveField(
            model_name='workflowstatestep',
            name='required_role_code',
        ),
    ]
