# Generated by Django 5.2.6 on 2025-10-03 21:43

import django.db.models.deletion
import django_mongodb_backend.fields
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0002_add_form_to_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRoleGroup',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_fa', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name_fa', models.CharField(max_length=128)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.orgrolegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.orgrole')),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SignatureLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.IntegerField(help_text='Form number where signature was applied')),
                ('field_path', models.CharField(help_text="JSON path to signature field (e.g., 'agreement.signature')", max_length=255)),
                ('signature_url', models.URLField(blank=True, help_text='DEPRECATED: No longer used', null=True)),
                ('signature_hash', models.CharField(help_text="User's signature hash at time of signing", max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Whether signature was verified at time of application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_logs', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_logs', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Signature Log',
                'verbose_name_plural': 'Signature Logs',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['workflow', 'form_number'], name='accounts_si_workflo_11fd99_idx'), models.Index(fields=['user', 'signed_at'], name='accounts_si_user_id_3cf258_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(blank=True, help_text='DEPRECATED: Digital signature is now hash-based', null=True, storage=storages.backends.s3.S3Storage(), upload_to='signatures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('signature_hash', models.CharField(help_text="Unique SHA256 hash representing user's digital signature", max_length=64, unique=True)),
                ('user', models.OneToOneField(help_text='User who owns this signature', on_delete=django.db.models.deletion.CASCADE, related_name='signature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Signature',
                'verbose_name_plural': 'User Signatures',
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_2bb1b9_idx')],
            },
        ),
    ]
