# Generated by Django 5.2.6 on 2025-10-03 22:03

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workflows', '0003_dynamicform_formfield_formsection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldPermission',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.IntegerField(help_text='Form number')),
                ('field_path', models.CharField(help_text="JSON path to field (e.g., 'personalInformation.firstName')", max_length=255)),
                ('permission_type', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('APPROVE', 'Approve'), ('TRANSITION', 'Transition State'), ('DELETE', 'Delete')], help_text='Type of permission', max_length=32)),
                ('state', models.CharField(blank=True, help_text='Optional: Restrict permission to specific state', max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='accounts.orgrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Field Permission',
                'verbose_name_plural': 'Form Field Permissions',
                'indexes': [models.Index(fields=['form_number', 'field_path', 'role'], name='permissions_form_nu_971b7a_idx'), models.Index(fields=['form_number', 'field_path', 'user'], name='permissions_form_nu_b5b052_idx'), models.Index(fields=['form_number', 'state'], name='permissions_form_nu_6061da_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormPermission',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.IntegerField(help_text='Form number (1, 2, 3, etc.)')),
                ('permission_type', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('APPROVE', 'Approve'), ('TRANSITION', 'Transition State'), ('DELETE', 'Delete')], help_text='Type of permission', max_length=32)),
                ('state', models.CharField(blank=True, help_text='Optional: Restrict permission to specific state', max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_permissions', to='accounts.orgrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Permission',
                'verbose_name_plural': 'Form Permissions',
                'indexes': [models.Index(fields=['form_number', 'permission_type', 'role'], name='permissions_form_nu_20ce54_idx'), models.Index(fields=['form_number', 'permission_type', 'user'], name='permissions_form_nu_899689_idx'), models.Index(fields=['form_number', 'state'], name='permissions_form_nu_2aa0e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('APPROVE', 'Approve'), ('TRANSITION', 'Transition State'), ('DELETE', 'Delete')], max_length=32)),
                ('form_number', models.IntegerField(blank=True, null=True)),
                ('field_path', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time for this override', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for override')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_permission_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Permission Override',
                'verbose_name_plural': 'Permission Overrides',
                'indexes': [models.Index(fields=['workflow', 'user', 'permission_type'], name='permissions_workflo_30c523_idx'), models.Index(fields=['expires_at'], name='permissions_expires_cade14_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatePermission',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='Workflow state name', max_length=64)),
                ('permission_type', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('APPROVE', 'Approve'), ('TRANSITION', 'Transition State'), ('DELETE', 'Delete')], help_text='Type of permission', max_length=32)),
                ('restrict_to_own', models.BooleanField(default=False, help_text="If True, permission only applies to user's own workflows")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_permissions', to='accounts.orgrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'State Permission',
                'verbose_name_plural': 'State Permissions',
                'indexes': [models.Index(fields=['state', 'permission_type', 'role'], name='permissions_state_ebd374_idx'), models.Index(fields=['state', 'permission_type', 'user'], name='permissions_state_afd939_idx')],
            },
        ),
        migrations.CreateModel(
            name='StateStepPermission',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='Workflow state name', max_length=64)),
                ('step', models.IntegerField(help_text='Step index (0-based)')),
                ('section', models.CharField(blank=True, help_text="Form section this step operates on (e.g., 'legalDeputyReport')", max_length=128, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('FILL', 'Fill Section'), ('APPROVE', 'Approve/Sign Section')], help_text='Type of action for this step', max_length=32, null=True)),
                ('signature_field', models.CharField(blank=True, help_text='Field path for signature if action is APPROVE', max_length=128, null=True)),
                ('description', models.CharField(blank=True, help_text='Persian description of step action', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_permissions', to='accounts.orgrole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'State Step Permission',
                'verbose_name_plural': 'State Step Permissions',
                'indexes': [models.Index(fields=['state', 'step', 'role'], name='permissions_state_73a214_idx'), models.Index(fields=['state', 'step', 'user'], name='permissions_state_01c7f0_idx')],
                'unique_together': {('state', 'step', 'role'), ('state', 'step', 'user')},
            },
        ),
    ]
