# Generated by Django 5.2.6 on 2025-10-06 12:34

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('permissions', '0001_initial'),
        ('workflows', '0004_convert_role_code_to_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code for this state (e.g., 'Form1', 'Form3_LegalReview')", max_length=64, unique=True)),
                ('name_en', models.CharField(help_text='English name', max_length=128)),
                ('name_fa', models.CharField(help_text='Persian name', max_length=128)),
                ('form_number', models.IntegerField(blank=True, help_text='Form number if this state represents a form', null=True)),
                ('form_section', models.CharField(blank=True, help_text='Form section code if this state represents a form section', max_length=128, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in workflow progression')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow State',
                'verbose_name_plural': 'Workflow States',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStateStep',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='Step number within the state (0-based)')),
                ('name_en', models.CharField(help_text='English name', max_length=128)),
                ('name_fa', models.CharField(help_text='Persian name', max_length=128)),
                ('description_fa', models.TextField(blank=True, help_text='Persian description of what this step does')),
                ('action_type', models.CharField(choices=[('FILL', 'Fill/Edit'), ('APPROVE', 'Approve'), ('SIGN', 'Sign'), ('REVIEW', 'Review')], default='APPROVE', help_text='Type of action required', max_length=32)),
                ('signature_field', models.CharField(blank=True, help_text='Field path for signature if action requires signing', max_length=128, null=True)),
                ('requires_all_approvers', models.BooleanField(default=False, help_text='If True, all assigned roles must approve. If False, any one role can approve (parallel)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='permissions.workflowstate')),
            ],
            options={
                'verbose_name': 'Workflow State Step',
                'verbose_name_plural': 'Workflow State Steps',
                'ordering': ['state', 'step_number'],
                'unique_together': {('state', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='StepPermissionOverride',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time for this override', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for override')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_simplified_permission_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplified_permission_overrides', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplified_permission_overrides', to='workflows.workflow')),
                ('step', models.ForeignKey(blank=True, help_text='Specific step to grant access to', null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.workflowstatestep')),
            ],
            options={
                'verbose_name': 'Step Permission Override',
                'verbose_name_plural': 'Step Permission Overrides',
                'indexes': [models.Index(fields=['workflow', 'user'], name='permissions_workflo_966542_idx'), models.Index(fields=['expires_at'], name='permissions_expires_d10558_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStateStepPermission',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simplified_step_permissions', to='accounts.orgrole')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_permissions', to='permissions.workflowstatestep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simplified_step_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow State Step Permission',
                'verbose_name_plural': 'Workflow State Step Permissions',
                'indexes': [models.Index(fields=['step', 'role'], name='permissions_step_id_39bc93_idx'), models.Index(fields=['step', 'user'], name='permissions_step_id_7a4132_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepCompletion',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('role_code', models.CharField(blank=True, help_text='Role code used for this completion', max_length=64, null=True)),
                ('data_snapshot', models.JSONField(blank=True, help_text='Snapshot of form data at time of completion', null=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_steps', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='permissions.workflowstatestep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Step Completion',
                'verbose_name_plural': 'Workflow Step Completions',
                'indexes': [models.Index(fields=['workflow', 'step'], name='permissions_workflo_3939b9_idx'), models.Index(fields=['completed_by', 'completed_at'], name='permissions_complet_9240a5_idx')],
            },
        ),
    ]
