# Generated by Django 5.2.6 on 2025-09-10 21:42

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('state', django_fsm.FSMField(choices=[('ApplicantRequest', 'Applicantrequest'), ('CEOInstruction', 'Ceoinstruction'), ('Form1', 'Form1'), ('Form2', 'Form2'), ('DocsCollection', 'Docscollection'), ('Form3', 'Form3'), ('Form4', 'Form4'), ('AMLForm', 'Amlform'), ('EvaluationCommittee', 'Evaluationcommittee'), ('AppraisalFeeDeposit', 'Appraisalfeedeposit'), ('AppraisalNotice', 'Appraisalnotice'), ('AppraisalOpinion', 'Appraisalopinion'), ('AppraisalDecision', 'Appraisaldecision'), ('Settlment', 'Settlment')], default='ApplicantRequest', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_id', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('step', models.IntegerField()),
                ('role_code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['letter_id', 'state'], name='letters_app_letter__38a24f_idx')],
                'unique_together': {('letter_id', 'state', 'step')},
            },
        ),
    ]
